export const games = [
  "The Witcher 2",
  "The Witcher 3",
  "Pathfinder Wrath of the Righteous",
  "Sid Meier's Civilization VI",
  "Path of Exile",
  "V Rising",
  "Fallout 4",
  "Fallout New  Vegas",
  "Metro 2033",
  "Divinity: Original Sin 2",
  "Ni No kuni: Wrath of the White Witch",
  "Resident Evil 2",
  "Resident Evil 3",
  "Titan Fall 2",
  "V  Rising",
  "Yakuza 0",
  "Stardew Valley",
  "Nioh",
  "Thronebreaker",
];
